ckpt_path: ../overfit/120_img.ckpt
device: 'cuda:0'
output_path: ../vid/test.mp4
playback_speed: 2

border: 3

runs:
  - seed: [1, 2, 3]
    num_of_runs: 3
  - seed: [1, 2, 3]
    num_of_runs: 3
  - seed: random
    num_of_runs: 3


# runs:
#   - seed: random
#     num_of_runs: 4
#     game_params:
#       - sheep_top_right: False
#   - seed: random
#     num_of_runs: 4
#     game_params:
#       - random_goal: True
