name: conversion_test

data_dir: data/
output_file: converted
image_shape: [3, 230, 230]

# Data folders to include, inclusive. In this example,
# all folders, 1-16, will be included
data:
  - start: 1
    end: 7
  - start: 8
    end: 51
  


decimation_factor: 1 # Decimation factor for the data

