name: conversion_test

data_dir: cons_goal/
output_file: cons_goal_converted
image_shape: [3, 130, 130]

# Data folders to include, inclusive. In this example,
# all folders, 1-16, will be included
data:
  - start: 1
    end: 7
  - start: 8
    end: 65
  


decimation_factor: 1 # Decimation factor for the data

