name: conversion_test

data_dir: com_dog_dist/
output_file: com_dog_dist_converted
image_shape: [3, 180, 180]

# Data folders to include, inclusive. In this example,
# all folders, 1-16, will be included
data:
  - start: 1
    end: 7
  - start: 8
    end: 100
  


decimation_factor: 1 # Decimation factor for the data

