defaults:
  - _self_
  - data_conversion: data_conversion

name: sheep_image

dataset_path: ../converted.zarr

# Shapes must match the data conversion config file
image_shape: &image_shape ${task.data_conversion.image_shape}
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: *image_shape
      type: rgb
    agent_pos:
      shape: [2]
      type: lowdim
  action:
    shape: [2]

env_runner:
  _target_: diffusion_policy.env_runner.sheep_image_runner.SheepImageRunner

dataset:
  _target_: diffusion_policy.dataset.sheep_image_dataset.SheepDataset
  zarr_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null